apiVersion: backstage.io/v1alpha1
kind: Component
  metadata:
    name: red_peters
    description: {The red_peters module for vets-api}
    tags:
      - ruby
      - rails
    annotations: 
      backstage.io/view-url: https://github.com/mhaley37/vets-api/blob/master/modules/red_peters/catalog-info.yaml
      backstage.io/edit-url: https://github.com/mhaley37/vets-api/edit/master/modules/red_peters/catalog-info.yaml
      backstage.io/source-location: https://github.com/mhaley37/vets-api/tree/master/modules/red_peters/
  spec:
    type: service
    owner: platform-console-services
    lifecycle: experimental
    subcomponentOf: vets-api
