name: Ensure Review Instance Bootable

on: deployment_status

jobs:
  deployment-status:
    runs-on: asg

    # Continue only if some definitive status has been reported.
    if: github.event.deployment_status.state != 'pending'

    steps:
      # Forward deployment's status to the deployed commit.
      - uses: octokit/request-action@v2.1.4
        # TODO: Is this env var needed?
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/department-of-veterans-affairs/vets-api/statuses/${{ github.event.deployment.sha }}
          repository: ${{ github.repository }}
          state: ${{ github.event.deployment_status.state }}
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          description: >
            ${{ format('Heroku deployment is {0}', github.event.deployment_status.state) }}
          context: deployment-status

  health-check:
    runs-on: asg

    # Run health check only if deployment succeeds.
    if: github.event.deployment_status.state == 'success'

    # Check that the deployed app returns successful HTTP response.
    steps:
    - run: echo "${{ fromJSON(github.event.deployment.payload) }}"
    - id: health_check
      uses: jtalk/url-health-check-action@v1.3
      with:
        url: ${{ github.event.deployment.payload.web_url }}
        follow-redirect: true
        max-attempts: 4
        retry-delay: 30s
      continue-on-error: true

    # Set appropriate status to the deployed commit.
    - uses: octokit/request-action@v2.1.4
      # TODO: Is this env var needed?
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        route: POST /repos/department-of-veterans-affairs/vets-api/statuses/${{ github.event.deployment.sha }}
        repository: ${{ github.repository }}
        state: ${{ steps.health_check.outcome }}
        target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        description: >
                    ${{ format('Site health is {0}', steps.health_check.outcome) }}
        context: health-check
